name: cronjob

on:
  schedule:
  - cron: "10 22 * * *" # every day at 10:10 pm (UTC)
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-20.04
    
    environment: marketeye-api

    env: 
      API_KEY: ${{ secrets.API_KEY }}
      DEV_RECIEVER_EMAIL: ${{ secrets.DEV_RECIEVER_EMAIL }}
      DEV_SENDER_EMAIL: ${{ secrets.DEV_SENDER_EMAIL }}
      DEV_SENDER_SERVICE: ${{ secrets.DEV_SENDER_SERVICE }}
      DEV_SENDER_SERVICE_PASSWORD: ${{ secrets.DEV_SENDER_SERVICE_PASSWORD }}
      DEV_SENDER_SERVICE_PORT: ${{ secrets.DEV_SENDER_SERVICE_PORT }}
      MI_BASE_URL: ${{ secrets.MI_BASE_URL }}
      MI_SP500_CODE: ${{ secrets.MI_SP500_CODE }}
      MI_SP500_DATASET: ${{ secrets.MI_SP500_DATASET }}
      MI_VIX_CODE: ${{ secrets.MI_VIX_CODE }}
      MI_VIX_DATASET: ${{ secrets.MI_VIX_DATASET }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      PING_URL: ${{ secrets.PING_URL }}
      QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}
      QUANDL_RATE_LIMIT: ${{ secrets.QUANDL_RATE_LIMIT }}
      QUANDL_SLEEP_MINUTES: ${{ secrets.QUANDL_SLEEP_MINUTES }}
      USER_AGENT: ${{ secrets.USER_AGENT }}
      DATE_TO_SCRAPE: ${{ secrets.DATE_TO_SCRAPE }}
      REDIS_URI: ${{ secrets.REDIS_URI }}
      YAHOO_BASE_FCF_URL: ${{ secrets.YAHOO_BASE_FCF_URL }}

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"

      - name: Installing webdriver-manager
        run: pip install webdriver-manager

      - name: Update stocks 'analytics' collection
        run: python cronjob.py
