name: cronjob

on:
  schedule:
    - cron: "00 19 * * *" # every day at 07:00 pm (UTC)
    - cron: "30 20 * * *" # every day at 08:30 pm (UTC)
    - cron: "00 22 * * *" # every day at 10:00 pm (UTC)
    - cron: "30 23 * * *" # every day at 11:30 pm (UTC)
  workflow_dispatch:
    inputs:
      target_date:
        description: "Target date, for whcih the calculations should be done. The required format is YYYY-MM-DD"
        required: false
        type: string
      additional_dev_receiver_email:
        description: "Another email to send the completion status of the cronjob"
        required: false
        default: "sun.anzhe@yahoo.com"

concurrency:
  group: read_markets
  cancel-in-progress: true

jobs:
  job:
    runs-on: ubuntu-20.04

    environment: marketeye-api

    env:
      API_KEY: ${{ secrets.API_KEY }}
      DEV_RECIEVER_EMAIL: ${{ secrets.DEV_RECIEVER_EMAIL }}
      ADDITIONAL_DEV_RECIEVER_EMAIL: ${{ inputs.additional_dev_receiver_email }}
      DEV_SENDER_EMAIL: ${{ secrets.DEV_SENDER_EMAIL }}
      DEV_SENDER_SERVICE: ${{ secrets.DEV_SENDER_SERVICE }}
      DEV_SENDER_SERVICE_PASSWORD: ${{ secrets.DEV_SENDER_SERVICE_PASSWORD }}
      DEV_SENDER_SERVICE_PORT: ${{ secrets.DEV_SENDER_SERVICE_PORT }}
      MI_BASE_URL: ${{ secrets.MI_BASE_URL }}
      MI_SP500_CODE: ${{ secrets.MI_SP500_CODE }}
      MI_SP500_DATASET: ${{ secrets.MI_SP500_DATASET }}
      MI_VIX_CODE: ${{ secrets.MI_VIX_CODE }}
      MI_VIX_DATASET: ${{ secrets.MI_VIX_DATASET }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      PING_URL: ${{ secrets.PING_URL }}
      QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}
      QUANDL_RATE_LIMIT: ${{ secrets.QUANDL_RATE_LIMIT }}
      QUANDL_SLEEP_MINUTES: ${{ secrets.QUANDL_SLEEP_MINUTES }}
      USER_AGENT: ${{ secrets.USER_AGENT }}
      DATE_TO_SCRAPE: ${{ secrets.DATE_TO_SCRAPE }}
      YAHOO_BASE_FCF_URL: ${{ secrets.YAHOO_BASE_FCF_URL }}

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"

      - name: Installing webdriver-manager and scipy
        run: pip install webdriver-manager scipy

      - name: Reading Redis Credentials from Heroku CLI
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo "REDIS_URI=$(heroku config:get REDIS_URL -a marketeye-api)" >> $GITHUB_ENV

      - name: Update stocks 'analytics' collection
        run: python cronjob.py ${{ inputs.target_date }}
