name: healthcheck

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  healthcheck-job:
    runs-on: ubuntu-22.04
    environment: marketeye-api
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests python-dotenv

      - name: Run healthcheck monitor
        env:
          PING_URL: ${{ secrets.PING_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python scripts/healthcheck_monitor.py
