name: pinger

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  ping-job:
    runs-on: ubuntu-20.04
    environment: marketeye-api
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.9

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests typing

      - name: Execute Python script
        env:
          PING_URL: ${{ secrets.PING_URL }}
        run: python pinger.py
