# This is a basic workflow to help you get started with Actions

name: pinger

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: checkout repo content
      - uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: dependencies
        run: |
          python3 -m pip install requests typing

      - name: execute pinger
        env: 
          PING_URL: ${{ secrets.PING_URL }}
        run: python pinger.py
