name: pinger

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  ping-job:
    runs-on: ubuntu-20.04
    environment: marketeye-api
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.9

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests typing

      - name: Execute Python script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PING_URL: ${{ secrets.PING_URL }}
          DEV_RECIEVER_EMAIL: ${{ secrets.DEV_RECIEVER_EMAIL }}
          DEV_SENDER_EMAIL: ${{ secrets.DEV_SENDER_EMAIL }}
          DEV_SENDER_SERVICE: ${{ secrets.DEV_SENDER_SERVICE }}
          DEV_SENDER_SERVICE_PASSWORD: ${{ secrets.DEV_SENDER_SERVICE_PASSWORD }}
          DEV_SENDER_SERVICE_PORT: ${{ secrets.DEV_SENDER_SERVICE_PORT }}
        run: python pinger.py
